version: "3.7"

services:

  # Go開発用サービス
  app:
    build:
      context: .
      dockerfile: ./build/Dockerfile
    container_name: ddd-api-with-go-gin-app
    env_file:
      - .env
      - .env.docker
    image: ddd-api-with-go-gin:latest
    networks:
      - default
    tty: true
    volumes:
      - .:/go/src

networks:
  default:
    name: ddd-api-with-go-gin
