version: "3.7"

services:

  # API
  api:
    build:
      context: .
      dockerfile: build/api/Dockerfile
    container_name: ddd-api-with-go-gin-api
    depends_on:
      - db
    env_file:
      - .env
      - .env.docker
    image: ddd-api-with-go-gin:latest
    hostname: api
    networks:
      - default
    tty: true
    volumes:
      - .:/go/src

  # データベース
  db:
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    container_name: ddd-api-with-go-gin-db
    env_file:
      # NOTE: docker-compose.ymlで使用する変数を展開するために読み込む．
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: "Asia/Tokyo"
    image: mysql:5.7
    hostname: db
    ports:
      - "3308:3306"
    networks:
      - default
    volumes:
      - db_volume:/var/www/lib/mysql

volumes:
  db_volume:
    driver: local

networks:
  default:
    name: ddd-api-with-go-gin
