version: "3.7"

services:

  # アプリケーション
  app:
    build:
      context: .
      dockerfile: ./build/Dockerfile
    container_name: ddd-api-with-go-gin-app
    env_file:
      - .env
      - .env.docker
    image: ddd-api-with-go-gin:latest
    networks:
      - default
    tty: true
    volumes:
      - .:/go/src

  # データベース
  db:
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    container_name: ddd-api-with-go-gin-db
    env_file:
      - .env
    image: mysql:5.7
    ports:
      - "3308:3306"
    tty: true
    networks:
      - default
    volumes:
      - db_volume:/var/www/lib/mysql

volumes:
  db_volume:
    driver: local

networks:
  default:
    name: ddd-api-with-go-gin
